name: build

on:
  push:
    branches:
      - main

env:
  SKIP_PREFLIGHT_CHECK: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: yarn install
      - run: yarn run build
      - run: yarn run deploy
      - run: git config user.name "兰鑫"
      - run: git config user.email "1192065030@qq.com"
      # - run: yarn run gh-pages
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://cuilanxin.github.io/
          npx gh-pages -d build -u "兰鑫 <1192065030@qq.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}